git rm --cached ABC-da-INFORMATICA.aux
git rm --cached ABC-da-INFORMATICA.bbl
git rm --cached ABC-da-INFORMATICA.blg
git rm --cached ABC-da-INFORMATICA.idx
git rm --cached ABC-da-INFORMATICA.log
git rm --cached ABC-da-INFORMATICA.out
git rm --cached ABC-da-INFORMATICA.pdf
git rm --cached ABC-da-INFORMATICA.synctex.gz
git rm --cached ABC-da-INFORMATICA.tex
git rm --cached ABC-da-INFORMATICA.toc
git rm --cached ABC-INFORMATICA.aux
git rm --cached ABC-INFORMATICA.bbl
git rm --cached ABC-INFORMATICA.blg
git rm --cached ABC-INFORMATICA.idx
git rm --cached ABC-INFORMATICA.log
git rm --cached ABC-INFORMATICA.out
git rm --cached ABC-INFORMATICA.pdf
git rm --cached ABC-INFORMATICA.synctex.gz
git rm --cached ABC-INFORMATICA.tex
git rm --cached ABC-INFORMATICA.tex.old
git rm --cached ABC-INFORMATICA.toc
git rm --cached AMBIENTE-DE-TESTES.aux
git rm --cached AMBIENTE-DE-TESTES.log
git rm --cached AMBIENTE-DE-TESTES.pdf
git rm --cached AMBIENTE-DE-TESTES.synctex.gz
git rm --cached AMBIENTE-DE-TESTES.tex
git rm --cached arquivos.py
git rm --cached A-VERDADE.aux
git rm --cached A-VERDADE.log
git rm --cached A-VERDADE.out
git rm --cached A-VERDADE.pdf
git rm --cached A-VERDADE.synctex.gz
git rm --cached A-VERDADE.tex
git rm --cached A-VERDADE.toc
git rm --cached BNCC_Ensino Fundamental.xlsx
git rm --cached CAPITULOS-PROJETO.tex
git rm --cached chatgpt.tex
git rm --cached CODIGO-EFESTUS.tex
git rm --cached CODIGO-VIKING-2024.tex
git rm --cached CSV/*
git rm --cached curriculum-paulista.pdf
git rm --cached 'Curso Informática_01.pdf'
git rm --cached DOC-MINIMO-BUG.aux
git rm --cached DOC-MINIMO-BUG.bbl
git rm --cached DOC-MINIMO-BUG.blg
git rm --cached DOC-MINIMO-BUG.log
git rm --cached DOC-MINIMO-BUG.pdf
git rm --cached DOC-MINIMO-BUG.synctex.gz
git rm --cached DOC-MINIMO-BUG.tex
git rm --cached EFESTUS.aux
git rm --cached EFESTUS.bbl
git rm --cached EFESTUS.blg
git rm --cached EFESTUS.log
git rm --cached EFESTUS.out
git rm --cached EFESTUS.synctex.gz
git rm --cached EFESTUS.toc
git rm --cached ESCOLA.bbl
git rm --cached ESCOLA.blg
git rm --cached ESCOLA.idx
git rm --cached FLISOL/*
git rm --cached frozen-bubble.lnk
git rm --cached HEFESTUS.aux
git rm --cached HEFESTUS.bbl
git rm --cached HEFESTUS.blg
git rm --cached HEFESTUS.log
git rm --cached HEFESTUS.out
git rm --cached HEFESTUS.pdf
git rm --cached HEFESTUS.synctex.gz
git rm --cached HEFESTUS.tex
git rm --cached HEFESTUS.toc
git rm --cached IMG/*
git rm --cached IMG-GIT/*
git rm --cached INDEX.aux
git rm --cached INDEX.log
git rm --cached INDEX.out
git rm --cached INDEX.pdf
git rm --cached INDEX.synctex.gz
git rm --cached INDEX.tex
git rm --cached LISTA.sh
git rm --cached MAIN.aux
git rm --cached Main.emmx
git rm --cached MAIN.log
git rm --cached MAIN.out
git rm --cached MAIN.pdf
git rm --cached MAIN.synctex.gz
git rm --cached MAIN.tex
git rm --cached PROJETO.aux
git rm --cached PROJETO.bbl
git rm --cached PROJETO.blg
git rm --cached PROJETO-COMPUTADOR.pdf
git rm --cached PROJETO-COMPUTADOR.synctex.gz
git rm --cached PROJETO-COMPUTADOR.toc
git rm --cached PROJETO.emmx
git rm --cached PROJETO-FLISOL.pdf
git rm --cached PROJETO-FLISOL.tex
git rm --cached PROJETO.html
git rm --cached PROJETO.idx
git rm --cached PROJETO.log
git rm --cached PROJETO_obsoleto.pdf
git rm --cached PROJETO.out
git rm --cached PROJETO.pdf
git rm --cached PROJETO.synctex.gz
git rm --cached PROJETO.tex
git rm --cached PROTEUS/*
git rm --cached TeX-Comp/*
git rm --cached tomcat.sh
git rm --cached tomcat.sh.aux
git rm --cached VIKING-CODE.aux
git rm --cached VIKING-CODE.idx
git rm --cached VIKING-CODE.log
git rm --cached VIKING-CODE.out
git rm --cached VIKING-CODE.pdf
git rm --cached VIKING-CODE.synctex.gz
git rm --cached VIKING-CODE.tex
git rm --cached VIKING-CODE.tex.old
git rm --cached VIKING-CODE.toc
